/**
 * Demo server — lets you click through the entire licensed-checkout flow
 * locally with ZERO external accounts:
 *
 *   Buy Now → mock Stripe checkout (enter any name/email) → Pay →
 *   download page → real personalized .xlsx generated by the real pipeline
 *   code (license id, tokens swapped, private "storage" = in-memory).
 *
 * The edge functions are mocked at /functions/v1/* but they call the same
 * shared code the Supabase Edge Functions call (license.ts, personalize.ts,
 * email.ts). The only thing mocked is Stripe itself and the database.
 *
 * Usage: npm run demo   →  http://localhost:4321
 */

import { createServer } from 'node:http';
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { dirname, join, extname, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateLicenseId } from '../supabase/functions/_shared/license.ts';
import { personalizeWorkbook } from '../supabase/functions/_shared/personalize.ts';
import { buildWelcomeEmail } from '../supabase/functions/_shared/email.ts';
import { getProduct, PRODUCTS } from '../supabase/functions/_shared/config.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PORT = Number(process.env.PORT || 4321);

// ---- in-memory "database" + "private storage" ----
const licenses = new Map();   // licenseId -> record
const sessions = new Map();   // sessionId -> licenseId
const record = {
  bytes: null, fileName: '', licenseId: '', productId: '', productName: '',
  customerName: '', customerEmail: '', createdAt: '', downloadCount: 0,
};

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.xml': 'application/xml',
  '.txt': 'text/plain; charset=utf-8',
  '.md': 'text/plain; charset=utf-8',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.webmanifest': 'application/manifest+json',
};

const json = (res, body, status = 200) => {
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify(body));
};

function readBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => {
      try { resolve(JSON.parse(data || '{}')); } catch { resolve({}); }
    });
  });
}

function runPipeline(productId, customerName, customerEmail) {
  const product = getProduct(productId);
  if (!product) throw new Error(`Unknown product: ${productId}`);

  const licenseId = generateLicenseId();
  const master = new Uint8Array(readFileSync(join(ROOT, 'assets/masters', product.masterPath)));
  const personalized = personalizeWorkbook({ masterBytes: master, licenseId, customerName, customerEmail });
  const fileName = `${product.fileNamePrefix}_${licenseId}.xlsx`;

  const lic = { ...record };
  lic.bytes = personalized.bytes;
  lic.fileName = fileName;
  lic.licenseId = licenseId;
  lic.productId = productId;
  lic.productName = product.name;
  lic.customerName = customerName;
  lic.customerEmail = customerEmail;
  lic.createdAt = new Date().toISOString();
  licenses.set(licenseId, lic);

  // Email preview (the real template) → test-output/
  const outDir = join(ROOT, 'test-output');
  mkdirSync(outDir, { recursive: true });
  const email = buildWelcomeEmail({
    productName: product.name,
    customerName,
    customerEmail,
    licenseId,
    downloadPageUrl: `/download.html?license=${licenseId}`,
    siteUrl: '',
    supportEmail: 'ITBB@intheblackbudget.com',
  });
  writeFileSync(join(outDir, 'demo-email-preview.html'), email.html);

  return { lic, emailSubject: email.subject };
}

const DEMO_CHECKOUT_PAGE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Checkout (DEMO) — In The Black Budget</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:Inter,-apple-system,sans-serif;background:#f4f4f5;color:#0a0a0a;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1.5rem}
  .wrap{width:100%;max-width:26rem}
  .banner{background:#0a0a0a;color:#fff;text-align:center;font-size:.78rem;font-weight:600;letter-spacing:.02em;padding:.6rem;border-radius:.9rem .9rem 0 0}
  .card{background:#fff;border:1px solid #e5e7eb;border-radius:0 0 1.1rem 1.1rem;padding:1.75rem;box-shadow:0 1px 2px rgba(10,10,10,.04)}
  h1{font-size:1.2rem;font-weight:800;letter-spacing:-.02em}
  .sub{color:#6b7280;font-size:.85rem;margin-top:.35rem;line-height:1.5}
  .row{margin-top:1.1rem}
  label{display:block;font-size:.75rem;font-weight:600;color:#374151;margin-bottom:.3rem}
  input{width:100%;border:1px solid #d1d5db;border-radius:.6rem;padding:.65rem .75rem;font-size:.9rem;font-family:inherit}
  input:focus{outline:2px solid #0a0a0a;outline-offset:1px;border-color:transparent}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}
  .total{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e5e7eb;margin-top:1.25rem;padding-top:1rem;font-weight:700}
  .btn{width:100%;background:#0a0a0a;color:#fff;border:none;border-radius:999px;font-size:1rem;font-weight:600;padding:.95rem;margin-top:1.1rem;cursor:pointer;font-family:inherit}
  .btn:hover{background:#000}
  .btn:disabled{opacity:.6;cursor:wait}
  .err{display:none;color:#b91c1c;background:#fef2f2;border:1px solid #fecaca;border-radius:.6rem;padding:.6rem .75rem;font-size:.8rem;margin-top:1rem}
  .foot{color:#9ca3af;font-size:.72rem;text-align:center;margin-top:1rem;line-height:1.5}
</style>
</head>
<body>
<div class="wrap">
  <div class="banner">⚠ DEMO MODE — this is a sandbox checkout. No real payment is processed.</div>
  <div class="card">
    <h1 id="product-name">In The Black Premium Toolkit</h1>
    <p class="sub">This demo stands in for Stripe Checkout. Enter any name and email — they'll be stamped into your licensed workbook.</p>
    <form id="form">
      <div class="row"><label for="name">Full name</label><input id="name" name="name" placeholder="John Smith" required /></div>
      <div class="row"><label for="email">Email</label><input id="email" name="email" type="email" placeholder="john@email.com" required /></div>
      <div class="row"><label for="card">Card number (demo)</label><input id="card" value="4242 4242 4242 4242" disabled /></div>
      <div class="grid">
        <div class="row"><label for="exp">Expiry</label><input id="exp" value="12 / 34" disabled /></div>
        <div class="row"><label for="cvc">CVC</label><input id="cvc" value="123" disabled /></div>
      </div>
      <div class="total"><span>Total (one-time)</span><span id="price">$36</span></div>
      <div class="err" id="err"></div>
      <button class="btn" id="pay" type="submit">Pay</button>
    </form>
  </div>
  <p class="foot">The real flow uses Stripe for this step. After payment, Stripe's webhook triggers license generation, workbook personalization, private storage, and your download email.</p>
</div>
<script>
  var q = new URLSearchParams(location.search);
  var PRODUCTS = { essentials: {name:'In The Black Essentials',price:'$19'}, complete:{name:'In The Black Complete',price:'$39'}, premium:{name:'In The Black Premium Toolkit — Founding Offer',price:'$36'} };
  var p = PRODUCTS[q.get('product')] || PRODUCTS.premium;
  document.getElementById('product-name').textContent = p.name;
  document.getElementById('price').textContent = p.price;
  document.getElementById('form').addEventListener('submit', async function(ev){
    ev.preventDefault();
    var btn = document.getElementById('pay'); btn.disabled = true; btn.textContent = 'Processing…';
    var err = document.getElementById('err'); err.style.display = 'none';
    try {
      var res = await fetch('/functions/v1/demo-pay', {
        method: 'POST',
        headers: {'Content-Type':'application/json'},
        body: JSON.stringify({ product: q.get('product') || 'premium', name: document.getElementById('name').value, email: document.getElementById('email').value })
      });
      var data = await res.json();
      if (data.redirect) { location.href = data.redirect; return; }
      err.textContent = data.error || 'Something went wrong.';
      err.style.display = 'block';
    } catch(e) { err.textContent = 'Network error — try again.'; err.style.display = 'block'; }
    btn.disabled = false; btn.textContent = 'Pay';
  });
</script>
</body>
</html>`;

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);

  if (req.method === 'OPTIONS') {
    res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' });
    return res.end();
  }

  // ---- mocked edge functions ----
  if (url.pathname === '/functions/v1/create-checkout' && req.method === 'POST') {
    const body = await readBody(req);
    const product = body.product || 'premium';
    if (!getProduct(product)) return json(res, { error: `Unknown product "${product}"` }, 400);
    return json(res, { url: `/demo-checkout.html?product=${encodeURIComponent(product)}` });
  }

  if (url.pathname === '/functions/v1/demo-pay' && req.method === 'POST') {
    const body = await readBody(req);
    const name = (body.name || 'Demo Customer').trim();
    const email = (body.email || 'demo@example.com').trim();
    try {
      const { lic, emailSubject } = runPipeline(body.product || 'premium', name, email);
      const sessionId = 'DEMO_' + Math.random().toString(36).slice(2, 10);
      sessions.set(sessionId, lic.licenseId);
      console.log(`💳 demo payment → license ${lic.licenseId} issued for ${name} <${email}>`);
      console.log(`   email preview: test-output/demo-email-preview.html  (subject: "${emailSubject}")`);
      return json(res, { redirect: `/download.html?session_id=${sessionId}` });
    } catch (err) {
      console.error('demo-pay error:', err);
      return json(res, { error: err.message }, 500);
    }
  }

  if (url.pathname === '/functions/v1/get-download' && req.method === 'GET') {
    const licenseParam = url.searchParams.get('license');
    const sessionParam = url.searchParams.get('session_id');
    let lic = null;
    if (licenseParam) lic = licenses.get(licenseParam.trim().toUpperCase());
    else if (sessionParam) lic = licenses.get(sessions.get(sessionParam) || '');
    if (!lic) return json(res, { status: 'processing', retryInSeconds: 2 });
    lic.downloadCount += 1;
    return json(res, {
      status: 'ready',
      licenseId: lic.licenseId,
      productId: lic.productId,
      productName: lic.productName,
      customerName: lic.customerName,
      fileName: lic.fileName,
      downloadUrl: `/functions/v1/demo-file/${lic.licenseId}`,
      expiresInSeconds: 259200,
    });
  }

  if (url.pathname.startsWith('/functions/v1/demo-file/') && req.method === 'GET') {
    const lic = licenses.get(url.pathname.split('/').pop());
    if (!lic) return json(res, { error: 'File not found or link expired' }, 404);
    res.writeHead(200, {
      'Content-Type': MIME['.xlsx'],
      'Content-Disposition': `attachment; filename="${lic.fileName}"`,
      'Cache-Control': 'private, no-store',
    });
    return res.end(lic.bytes);
  }

  if (url.pathname === '/demo-checkout.html' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': MIME['.html'] });
    return res.end(DEMO_CHECKOUT_PAGE);
  }

  // ---- static site (with checkout base injected into content.json) ----
  let pathname = url.pathname === '/' ? '/index.html' : normalize(url.pathname);
  if (pathname === '/content.json') {
    const c = JSON.parse(readFileSync(join(ROOT, 'content.json'), 'utf8'));
    c.functionsBaseUrl = '/functions/v1'; // demo override — the real value is set in content.json for production
    res.writeHead(200, { 'Content-Type': MIME['.json'], 'Cache-Control': 'no-store' });
    return res.end(JSON.stringify(c));
  }

  let filePath = join(ROOT, pathname.replace(/^\/+/, ''));
  if (!existsSync(filePath) || !statSync(filePath).isFile()) {
    filePath = join(ROOT, '404.html');
    res.statusCode = 404;
  }
  const ext = extname(filePath).toLowerCase();
  res.writeHead(res.statusCode || 200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
  res.end(readFileSync(filePath));
});

server.listen(PORT, '0.0.0.0', () => {
  console.log('');
  console.log('═══ In The Black — licensed checkout demo ═══');
  console.log(`  Site:        http://localhost:${PORT}`);
  console.log(`  Try: Buy now → demo checkout → Pay → personalized download`);
  console.log(`  Products:    ${PRODUCTS.map((p) => p.id).join(', ')}`);
  console.log('');
});
