-- Pravely customer financial workspace.
-- Every row is owned by one authenticated Supabase user and protected by RLS.

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 160),
  current_amount numeric(14,2) not null default 0 check (current_amount >= 0),
  target_amount numeric(14,2) not null check (target_amount > 0),
  due_date date,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, id)
);

create table public.budget_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_type text not null check (entry_type in ('Income', 'Expense', 'Debt', 'Taxes', 'Investing', 'Subscription', 'Goal')),
  category text not null check (length(trim(category)) between 1 and 160),
  monthly_amount numeric(14,2) not null check (monthly_amount > 0),
  goal_id bigint,
  payment_method text check (payment_method is null or length(payment_method) <= 120),
  notes text check (notes is null or length(notes) <= 1000),
  is_card_benefit boolean not null default false,
  is_partial_benefit boolean not null default false,
  covered_amount numeric(14,2) not null default 0 check (covered_amount >= 0 and covered_amount <= monthly_amount),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budget_entries_goal_owner_fk foreign key (user_id, goal_id)
    references public.goals(user_id, id) on delete cascade,
  constraint budget_entries_goal_type_check check (
    (entry_type = 'Goal' and goal_id is not null) or
    (entry_type <> 'Goal' and goal_id is null)
  )
);

create table public.debts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 160),
  balance numeric(14,2) not null default 0 check (balance >= 0),
  interest_rate numeric(7,4) not null default 0 check (interest_rate between 0 and 100),
  minimum_payment numeric(14,2) not null default 0 check (minimum_payment >= 0),
  extra_payment numeric(14,2) not null default 0 check (extra_payment >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.net_worth_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null check (item_type in ('asset', 'liability')),
  name text not null check (length(trim(name)) between 1 and 160),
  amount numeric(14,2) not null default 0 check (amount >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dark_mode boolean not null default false,
  calculator_state jsonb not null default '{}'::jsonb check (jsonb_typeof(calculator_state) = 'object'),
  preferences jsonb not null default '{}'::jsonb check (jsonb_typeof(preferences) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index budget_entries_user_id_idx on public.budget_entries(user_id);
create index goals_user_id_idx on public.goals(user_id);
create index debts_user_id_idx on public.debts(user_id);
create index net_worth_items_user_id_idx on public.net_worth_items(user_id);

alter table public.budget_entries enable row level security;
alter table public.goals enable row level security;
alter table public.debts enable row level security;
alter table public.net_worth_items enable row level security;
alter table public.user_settings enable row level security;

revoke all on table public.budget_entries, public.goals, public.debts, public.net_worth_items, public.user_settings from anon, authenticated;
grant select, insert, update, delete on table public.budget_entries, public.goals, public.debts, public.net_worth_items, public.user_settings to authenticated;
grant usage, select on sequence public.budget_entries_id_seq, public.goals_id_seq, public.debts_id_seq, public.net_worth_items_id_seq to authenticated;

create policy "Customers read own budget entries" on public.budget_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy "Customers create own budget entries" on public.budget_entries for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Customers update own budget entries" on public.budget_entries for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Customers delete own budget entries" on public.budget_entries for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Customers read own goals" on public.goals for select to authenticated using ((select auth.uid()) = user_id);
create policy "Customers create own goals" on public.goals for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Customers update own goals" on public.goals for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Customers delete own goals" on public.goals for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Customers read own debts" on public.debts for select to authenticated using ((select auth.uid()) = user_id);
create policy "Customers create own debts" on public.debts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Customers update own debts" on public.debts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Customers delete own debts" on public.debts for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Customers read own net worth items" on public.net_worth_items for select to authenticated using ((select auth.uid()) = user_id);
create policy "Customers create own net worth items" on public.net_worth_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Customers update own net worth items" on public.net_worth_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Customers delete own net worth items" on public.net_worth_items for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Customers read own settings" on public.user_settings for select to authenticated using ((select auth.uid()) = user_id);
create policy "Customers create own settings" on public.user_settings for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Customers update own settings" on public.user_settings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Customers delete own settings" on public.user_settings for delete to authenticated using ((select auth.uid()) = user_id);
