-- One source of truth for web, PWA, iOS, and Android access.
create table if not exists public.app_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_id text not null default 'free' check (plan_id in ('free', 'plus', 'complete')),
  status text not null default 'active' check (status in ('active', 'refunded', 'revoked')),
  provider text not null default 'pravely' check (provider in ('pravely', 'stripe', 'apple', 'google')),
  provider_customer_id text,
  provider_transaction_id text,
  purchased_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.app_entitlements enable row level security;
revoke all on table public.app_entitlements from anon;
grant select on table public.app_entitlements to authenticated;
grant all on table public.app_entitlements to service_role;

drop policy if exists "Customers can view their own app entitlement" on public.app_entitlements;
create policy "Customers can view their own app entitlement"
on public.app_entitlements for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists app_entitlements_provider_transaction_idx
on public.app_entitlements (provider, provider_transaction_id)
where provider_transaction_id is not null;

-- Native push tokens are private to the owner and service role.
create table if not exists public.push_device_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('ios', 'android', 'web')),
  token text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform, token)
);

alter table public.push_device_tokens enable row level security;
revoke all on table public.push_device_tokens from anon;
grant select, insert, update, delete on table public.push_device_tokens to authenticated;
grant usage, select on sequence public.push_device_tokens_id_seq to authenticated;
grant all on table public.push_device_tokens to service_role;

create policy "Customers manage their own push devices"
on public.push_device_tokens for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
